Individual files and network access tools
LivingInSyn/RMML pull request #15
Opened 2023-11-18 19:09 UTC by LivingInSyn

This changes RMML from one big yaml file to many smaller easier to work with files.

It also includes ngrok and tailscale which aren't technically RMMs but fit the spirit of the mission of this repo

2023-11-19 02:26 UTC, LivingInSyn commented
Need to test the updated carbon black script before merge

2023-11-28 17:54 UTC, devinbfergy requested changes

2023-11-28 17:54 UTC, devinbfergy commented on README.md
> +The use case this was created for is a security team who wants to monitor their environment for RMMs that aren't supposed to be there (or for all of them). CI in the releases will include the content
Fix typo "incividual"

2023-11-28 17:54 UTC, devinbfergy commented on rmml/README.md
> +This is a dummy file to make poetry place nice
"play" instead of place.

2023-11-28 17:58 UTC, devinbfergy approved these changes

2023-11-28 18:03 UTC, merged